# Generated by Django 4.2.7 on 2023-12-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
